// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_config.proto

#ifndef PROTOBUF_game_5fconfig_2eproto__INCLUDED
#define PROTOBUF_game_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace legend {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_game_5fconfig_2eproto();
void protobuf_AssignDesc_game_5fconfig_2eproto();
void protobuf_ShutdownFile_game_5fconfig_2eproto();

class GameConfig;
class GameConfig_DisplayConfig;

// ===================================================================

class GameConfig_DisplayConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:legend.GameConfig.DisplayConfig) */ {
 public:
  GameConfig_DisplayConfig();
  virtual ~GameConfig_DisplayConfig();

  GameConfig_DisplayConfig(const GameConfig_DisplayConfig& from);

  inline GameConfig_DisplayConfig& operator=(const GameConfig_DisplayConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameConfig_DisplayConfig& default_instance();

  void Swap(GameConfig_DisplayConfig* other);

  // implements Message ----------------------------------------------

  inline GameConfig_DisplayConfig* New() const { return New(NULL); }

  GameConfig_DisplayConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameConfig_DisplayConfig& from);
  void MergeFrom(const GameConfig_DisplayConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GameConfig_DisplayConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 width = 1;
  void clear_width();
  static const int kWidthFieldNumber = 1;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // optional int32 height = 2;
  void clear_height();
  static const int kHeightFieldNumber = 2;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:legend.GameConfig.DisplayConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_5fconfig_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static GameConfig_DisplayConfig* default_instance_;
};
// -------------------------------------------------------------------

class GameConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:legend.GameConfig) */ {
 public:
  GameConfig();
  virtual ~GameConfig();

  GameConfig(const GameConfig& from);

  inline GameConfig& operator=(const GameConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameConfig& default_instance();

  void Swap(GameConfig* other);

  // implements Message ----------------------------------------------

  inline GameConfig* New() const { return New(NULL); }

  GameConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameConfig& from);
  void MergeFrom(const GameConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GameConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef GameConfig_DisplayConfig DisplayConfig;

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:legend.GameConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_5fconfig_2eproto();
  friend void protobuf_AssignDesc_game_5fconfig_2eproto();
  friend void protobuf_ShutdownFile_game_5fconfig_2eproto();

  void InitAsDefaultInstance();
  static GameConfig* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GameConfig_DisplayConfig

// optional int32 width = 1;
inline void GameConfig_DisplayConfig::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 GameConfig_DisplayConfig::width() const {
  // @@protoc_insertion_point(field_get:legend.GameConfig.DisplayConfig.width)
  return width_;
}
inline void GameConfig_DisplayConfig::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:legend.GameConfig.DisplayConfig.width)
}

// optional int32 height = 2;
inline void GameConfig_DisplayConfig::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 GameConfig_DisplayConfig::height() const {
  // @@protoc_insertion_point(field_get:legend.GameConfig.DisplayConfig.height)
  return height_;
}
inline void GameConfig_DisplayConfig::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:legend.GameConfig.DisplayConfig.height)
}

// -------------------------------------------------------------------

// GameConfig

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace legend

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_5fconfig_2eproto__INCLUDED
